# Generated by Django 4.2.3 on 2023-08-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('moderated', 'Модерированная'), ('rejected', 'Отклоненная')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
