# Generated by Django 4.2.3 on 2023-08-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
